### PR TITLE
Upgrade to nan 2.0.x

### PR DESCRIPTION
**Pull request by raymondfeng**
/To @bnoordhuis

### CODE REVIEW

**Comment by bnoordhuis** [comment]
The ubuntu-0.10 buildbot is failing with what looks like memory corruption:
 
```
*** Error in `node': free(): invalid size: 0x00007f38840292d0 ***
Aborted (core dumped)
```

The Windows build is failing with what looks like a missing `#include <time.h>`:

```
..\src\connection.cpp(904): error C2228: left of '.ToLocalChecked' must have class/struct/union [D:\workspace\strong-oracle.pr\cd6b86e3\build\oracle_bindings.vcxproj]
..\src\connection.cpp(904): error C3861: 'time': identifier not found [D:\workspace\strong-oracle.pr\cd6b86e3\build\oracle_bindings.vcxproj]
..\src\connection.cpp(920): error C2228: left of '.ToLocalChecked' must have class/struct/union [D:\workspace\strong-oracle.pr\cd6b86e3\build\oracle_bindings.vcxproj]
..\src\connection.cpp(920): error C3861: 'time': identifier not found [D:\workspace\strong-oracle.pr\cd6b86e3\build\oracle_bindings.vcxproj]
```

**Comment by raymondfeng** [comment]
@bnoordhuis I fixed the `time` issue. 

Can you help troubleshoot http://ci.strongloop.com/job/strong-oracle.pr/18/label=amazon-0.10/console? It seems that the crash is caused by GC of buffer.

**Comment by raymondfeng** [comment]
test please

**Comment by raymondfeng** [comment]
test please

**Comment by bnoordhuis** [comment]
It's possible that https://github.com/nodejs/node/pull/2912 fixes the GC crash.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Pull request merged**
