### PR TITLE
Added basic LONG RAW support.

### PR DESCRIPTION
**Pull request by pgkehle**
LONG_ROW_MAX_SIZE is currently set to 20MB.  Could change this to a required option.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by pgkehle** [comment]
This has never been merged.  Any thoughts to adding it to master?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jannyHou** [comment]
@pgkehle Thank you for contribution! Could you also create some test case to prove your change?

**Comment by pgkehle** [comment]
Hi, frankly, I have not yet made use of the newer testing tools (travis-ci) yet.  My test case was to pull from an old production server that had a table with a column that was of the type LONG RAW.  The data comes in as a text string that I can handle.  Not a whole lot to it I'm afraid.  

(Also, I apologize it's taken so long to reply -- this was lost amongst a sea of github notifications)

**Pull request merged**
